name: nishihara.me
markdown: kramdown
highlighter: rouge
github: https://github.com/anishihara
about: I am a developer and photography enthusiast.
paginate: 5
permalink: pretty
url: http://blog.nishihara.me
plugins: [jekyll-paginate]
urls:
    - text: twitter
      url: https://twitter.com/anishihara
    - text: github
      url: https://github.com/anishihara
    - text: flickr
      url: https://www.flickr.com/photos/90282328@N02/
