name: nishihara.me
markdown: redcarpet
highlighter: pygments
github: https://github.com/anishihara
about: I am a developer.
paginate: 5
permalink: pretty
urls:
    - text: twitter
      url: https://twitter.com/anishihara
    - text: github
      url: https://github.com/anishihara
