name: nishihara.me
markdown: redcarpet
highlighter: pygments
github: https://github.com/anishihara
about: I am a developer.
urls:
    - text: github
      url: https://github.com/anishihara
    - text: email
      url: mailto:anderson@nishihara.me
